Set MIX_ENV during Phoenix digest
labzero/bootleg_phoenix pull request #3
Opened 2017-08-01 22:36 UTC by rjanja

Corrects the current behavior of digest task not succeeding due to an assumed dev environment.

2017-08-01 23:21 UTC, holetse requested changes

2017-08-01 23:21 UTC, holetse commented on lib/bootleg/tasks/phoenix_digest.ex
> +      mix_env = Config.get_config(:mix_env, "prod")
It would be better to use the documented DSL verb `config`, and not an undocumented internal function here.

2017-08-01 23:23 UTC, holetse commented
This PR needs a test associated with the changes.

2017-08-02 01:15 UTC, rjanja commented on lib/bootleg/tasks/phoenix_digest.ex
> +      mix_env = Config.get_config(:mix_env, "prod")
The DSL verb you're advocating is not documented nor is it used by any of Bootleg's own tasks, so I strongly disagree with you here.

2017-08-02 01:43 UTC, rjanja commented
As it stands, this package doesn't work for a vanilla Phoenix 1.2 project. The test you are suggesting already exists, it's just not actually throwing an error and failing for reasons I've pointed out in #2 and again in #5. That fix has been separated into another PR at your request. At this point I'm feeling a little discouraged about my contributions back to the project, so maybe it'd be best for me to maintain a fork that works for my purposes and file upstream issues as I encounter them.

2017-08-02 01:43 UTC, closed without merging